// This file was auto-generated by Fern from our API Definition.

export interface GetConcurrencyResponse {
    account_id: string;
    concurrent_calls: number;
    max_concurrent: number;
    utilization_pct: number;
    request_id: string;
}
