// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         currency: "INR"
 *     }
 */
export interface GetBalanceRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Currency code (e.g. INR, USD) */
    currency: string;
}
