// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX"
 *     }
 */
export interface ListTransactionsRequest {
    /** Your account Auth ID */
    auth_id: string;
    limit?: number;
    offset?: number;
}
