// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         from_date: "2026-08-25",
 *         to_date: "2026-08-25",
 *         type: "debit",
 *         currency: "INR",
 *         reference_type: "cdr"
 *     }
 */
export interface ListTransactionsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Page number, 1-indexed. */
    page?: number;
    /** Records per page. A value above the maximum falls back to the default of 50 rather than clamping. */
    per_page?: number;
    /** Start of the window, inclusive. Date-only or full ISO 8601 timestamp. Day boundaries are UTC. */
    from_date?: string;
    /** End of the window, inclusive. A date-only value covers the whole day. */
    to_date?: string;
    /** `credit` or `debit` act as broad classifications and sweep in legacy entry types such as `did_rental`; any other value is an exact match on `transactions[].type`. */
    type?: string;
    /** Exact match on transaction status. */
    status?: Vobiz.ListTransactionsRequestStatus;
    /** Currency code. Uppercased server-side, exact match. */
    currency?: string;
    /** Spend source, matching `transactions[].reference_type`. */
    reference_type?: string;
    /** Case-insensitive substring match on the description. */
    description?: string;
    /** Case-insensitive substring match on the reference. */
    reference?: string;
    /** Fetch a single ledger entry by its UUID. */
    transaction_id?: string;
}
