// This file was auto-generated by Fern from our API Definition.

export interface GetBalanceResponse {
    id: string;
    account_id: string;
    currency: string;
    balance: number;
    reserved_funds: number;
    promotional_balance: number;
    promotional_reserved_balance: number;
    available_balance: number;
    credit_limit: number;
    is_postpaid: boolean;
    credit_limit_type: string;
    low_balance_threshold: number;
    status: string;
    created_at: string;
    updated_at: string;
}
