// This file was auto-generated by Fern from our API Definition.

export const ListTransactionsRequestStatus = {
    Completed: "completed",
    Pending: "pending",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type ListTransactionsRequestStatus =
    (typeof ListTransactionsRequestStatus)[keyof typeof ListTransactionsRequestStatus];
