// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "call_uuid",
 *         text: "Hello, your appointment is confirmed for tomorrow at 3 PM.",
 *         voice: "WOMAN",
 *         language: "en-US"
 *     }
 */
export interface SpeakTextCallRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    text: string;
    voice?: string;
    language?: string;
    legs?: SpeakTextCallRequest.Legs;
}

export namespace SpeakTextCallRequest {
    export const Legs = {
        Aleg: "aleg",
        Bleg: "bleg",
        Both: "both",
    } as const;
    export type Legs = (typeof Legs)[keyof typeof Legs];
}
