// This file was auto-generated by Fern from our API Definition.

export interface ListCredentialsResponse {
    meta: ListCredentialsResponse.Meta;
    objects: ListCredentialsResponse.Objects.Item[];
}

export namespace ListCredentialsResponse {
    export interface Meta {
        limit: number;
        offset: number;
        total: number;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            id: string;
            account_id: string;
            username: string;
            password: string;
            realm: string;
            enabled: boolean;
            created_at: string;
            updated_at: string;
        }
    }
}
