// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

export interface ExportCdrsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Filter by the originating phone number (caller). */
    from_number?: string;
    /** Filter by the destination phone number (callee). */
    to_number?: string;
    /** Beginning of the search period (YYYY-MM-DD). Required when using `end_date`. */
    start_date?: string;
    /** End of the search period (YYYY-MM-DD). Required when using `start_date`. */
    end_date?: string;
    /** Filter by direction. */
    call_direction?: Vobiz.ExportCdrsRequestCallDirection;
    /** Minimum call duration in seconds. Excludes calls shorter than this value. */
    min_duration?: number;
    /** Filter by the SIP Call-ID of the call (matches the cdr's sip_call_id field). */
    sip_call_id?: string;
    /** Filter by the UUID of the bridged leg (matches the cdr's bridge_uuid field). */
    bridge_uuid?: string;
    /** Filter by telephony hangup cause, e.g. NORMAL_CLEARING. */
    hangup_cause?: string;
    /** Filter by how the leg was released, e.g. send_refuse. */
    hangup_disposition?: string;
    /** Filter by the call context, e.g. sip-trunking. */
    context?: string;
    /** Filter by the campaign identifier associated with the call. */
    campaign_id?: string;
    /** Free-text search across CDR fields (numbers, IDs, etc.). */
    search?: string;
}
