// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_id: "abc123-def456-ghi789"
 *     }
 */
export interface GetCdrRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The unique call ID of the completed call. */
    call_id: string;
}
