// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         from_number: "9876543210",
 *         to_number: "1234567890",
 *         start_date: "2026-03-01",
 *         end_date: "2026-03-17",
 *         min_duration: 10
 *     }
 */
export interface ListCdrsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Filter by the originating phone number (caller). */
    from_number?: string;
    /** Filter by the destination phone number (callee). */
    to_number?: string;
    /** Beginning of the search period (YYYY-MM-DD). Required when using `end_date`. */
    start_date?: string;
    /** End of the search period (YYYY-MM-DD). Required when using `start_date`. */
    end_date?: string;
    /** Filter by direction. */
    call_direction?: Vobiz.ListCdrsRequestCallDirection;
    /** Minimum call duration in seconds. Excludes calls shorter than this value. */
    min_duration?: number;
    /** Page number for paginated results. */
    page?: number;
    /** Number of records per page. Max: 100. */
    per_page?: number;
}
