// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         from_number: "9876543210",
 *         to_number: "1234567890",
 *         start_date: "2026-03-01",
 *         end_date: "2026-03-17",
 *         min_duration: 10,
 *         sip_call_id: "dD1qwu5VZ5iK3ed5u3uspjY5RKL",
 *         bridge_uuid: "4b7ae653-f40d-42f1-b582-6b05dfcd0c0a",
 *         hangup_cause: "NORMAL_CLEARING",
 *         hangup_disposition: "send_refuse",
 *         context: "sip-trunking"
 *     }
 */
export interface ListCdrsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Filter by the originating phone number (caller). */
    from_number?: string;
    /** Filter by the destination phone number (callee). */
    to_number?: string;
    /** Beginning of the search period (YYYY-MM-DD). Required when using `end_date`. */
    start_date?: string;
    /** End of the search period (YYYY-MM-DD). Required when using `start_date`. */
    end_date?: string;
    /** Filter by direction. */
    call_direction?: Vobiz.ListCdrsRequestCallDirection;
    /** Minimum call duration in seconds. Excludes calls shorter than this value. */
    min_duration?: number;
    /** Filter by the SIP Call-ID of the call (matches the cdr's sip_call_id field). */
    sip_call_id?: string;
    /** Filter by the UUID of the bridged leg (matches the cdr's bridge_uuid field). */
    bridge_uuid?: string;
    /** Filter by telephony hangup cause, e.g. NORMAL_CLEARING. */
    hangup_cause?: string;
    /** Filter by how the leg was released, e.g. send_refuse. */
    hangup_disposition?: string;
    /** Filter by the call context, e.g. sip-trunking. */
    context?: string;
    /** Filter by the campaign identifier associated with the call. */
    campaign_id?: string;
    /** Free-text search across CDR fields (numbers, IDs, etc.). */
    search?: string;
    /** Page number for paginated results. */
    page?: number;
    /** Number of records per page. Max: 100. */
    per_page?: number;
}
