// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         limit: 50
 *     }
 */
export interface ListRecentCdrsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Number of recent CDRs to return. */
    limit?: number;
}
