// This file was auto-generated by Fern from our API Definition.

export interface ListEndpointsResponse {
    api_id: string;
    meta: ListEndpointsResponse.Meta;
    objects: ListEndpointsResponse.Objects.Item[];
}

export namespace ListEndpointsResponse {
    export interface Meta {
        limit: number;
        offset: number;
        total_count: number;
        next: unknown | null;
        previous: unknown | null;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            alias: string;
            application: string | null;
            endpoint_id: string;
            resource_uri: string;
            sip_registered: string;
            sip_uri: string;
            sub_account: unknown | null;
            username: string;
        }
    }
}
