// This file was auto-generated by Fern from our API Definition.

export interface RetrieveEndpointResponse {
    alias: string;
    application: string;
    endpoint_id: string;
    resource_uri: string;
    sip_registered: string;
    sip_uri: string;
    sub_account: unknown | null;
    username: string;
}
