// This file was auto-generated by Fern from our API Definition.

import { AccountClient } from "./api/resources/account/client/Client.js";
import { ApplicationsClient } from "./api/resources/applications/client/Client.js";
import { AudioStreamsClient } from "./api/resources/audioStreams/client/Client.js";
import { BalanceClient } from "./api/resources/balance/client/Client.js";
import { CallsClient } from "./api/resources/calls/client/Client.js";
import { CdrClient } from "./api/resources/cdr/client/Client.js";
import { ConferenceClient } from "./api/resources/conference/client/Client.js";
import { ConferenceMembersClient } from "./api/resources/conferenceMembers/client/Client.js";
import { ConferenceRecordingClient } from "./api/resources/conferenceRecording/client/Client.js";
import { ConferencesClient } from "./api/resources/conferences/client/Client.js";
import { CredentialsClient } from "./api/resources/credentials/client/Client.js";
import { DtmfClient } from "./api/resources/dtmf/client/Client.js";
import { EndpointsClient } from "./api/resources/endpoints/client/Client.js";
import { IpAccessControlListClient } from "./api/resources/ipAccessControlList/client/Client.js";
import { LiveCallsClient } from "./api/resources/liveCalls/client/Client.js";
import { OriginationUriClient } from "./api/resources/originationUri/client/Client.js";
import { PartnerApiClient } from "./api/resources/partnerApi/client/Client.js";
import { PhoneNumbersClient } from "./api/resources/phoneNumbers/client/Client.js";
import { PlayAudioClient } from "./api/resources/playAudio/client/Client.js";
import { RecordCallsClient } from "./api/resources/recordCalls/client/Client.js";
import { RecordingsClient } from "./api/resources/recordings/client/Client.js";
import { SpeakTextClient } from "./api/resources/speakText/client/Client.js";
import { SubAccountKycClient } from "./api/resources/subAccountKyc/client/Client.js";
import { SubAccountKycTestModeClient } from "./api/resources/subAccountKycTestMode/client/Client.js";
import { SubAccountsClient } from "./api/resources/subAccounts/client/Client.js";
import { TrunksClient } from "./api/resources/trunks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace VobizClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class VobizClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<VobizClient.Options>;
    protected _account: AccountClient | undefined;
    protected _balance: BalanceClient | undefined;
    protected _liveCalls: LiveCallsClient | undefined;
    protected _calls: CallsClient | undefined;
    protected _cdr: CdrClient | undefined;
    protected _subAccounts: SubAccountsClient | undefined;
    protected _subAccountKyc: SubAccountKycClient | undefined;
    protected _subAccountKycTestMode: SubAccountKycTestModeClient | undefined;
    protected _phoneNumbers: PhoneNumbersClient | undefined;
    protected _trunks: TrunksClient | undefined;
    protected _conference: ConferenceClient | undefined;
    protected _recordCalls: RecordCallsClient | undefined;
    protected _playAudio: PlayAudioClient | undefined;
    protected _speakText: SpeakTextClient | undefined;
    protected _dtmf: DtmfClient | undefined;
    protected _audioStreams: AudioStreamsClient | undefined;
    protected _conferences: ConferencesClient | undefined;
    protected _conferenceMembers: ConferenceMembersClient | undefined;
    protected _conferenceRecording: ConferenceRecordingClient | undefined;
    protected _recordings: RecordingsClient | undefined;
    protected _credentials: CredentialsClient | undefined;
    protected _ipAccessControlList: IpAccessControlListClient | undefined;
    protected _originationUri: OriginationUriClient | undefined;
    protected _applications: ApplicationsClient | undefined;
    protected _endpoints: EndpointsClient | undefined;
    protected _partnerApi: PartnerApiClient | undefined;

    constructor(options: VobizClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get account(): AccountClient {
        return (this._account ??= new AccountClient(this._options));
    }

    public get balance(): BalanceClient {
        return (this._balance ??= new BalanceClient(this._options));
    }

    public get liveCalls(): LiveCallsClient {
        return (this._liveCalls ??= new LiveCallsClient(this._options));
    }

    public get calls(): CallsClient {
        return (this._calls ??= new CallsClient(this._options));
    }

    public get cdr(): CdrClient {
        return (this._cdr ??= new CdrClient(this._options));
    }

    public get subAccounts(): SubAccountsClient {
        return (this._subAccounts ??= new SubAccountsClient(this._options));
    }

    public get subAccountKyc(): SubAccountKycClient {
        return (this._subAccountKyc ??= new SubAccountKycClient(this._options));
    }

    public get subAccountKycTestMode(): SubAccountKycTestModeClient {
        return (this._subAccountKycTestMode ??= new SubAccountKycTestModeClient(this._options));
    }

    public get phoneNumbers(): PhoneNumbersClient {
        return (this._phoneNumbers ??= new PhoneNumbersClient(this._options));
    }

    public get trunks(): TrunksClient {
        return (this._trunks ??= new TrunksClient(this._options));
    }

    public get conference(): ConferenceClient {
        return (this._conference ??= new ConferenceClient(this._options));
    }

    public get recordCalls(): RecordCallsClient {
        return (this._recordCalls ??= new RecordCallsClient(this._options));
    }

    public get playAudio(): PlayAudioClient {
        return (this._playAudio ??= new PlayAudioClient(this._options));
    }

    public get speakText(): SpeakTextClient {
        return (this._speakText ??= new SpeakTextClient(this._options));
    }

    public get dtmf(): DtmfClient {
        return (this._dtmf ??= new DtmfClient(this._options));
    }

    public get audioStreams(): AudioStreamsClient {
        return (this._audioStreams ??= new AudioStreamsClient(this._options));
    }

    public get conferences(): ConferencesClient {
        return (this._conferences ??= new ConferencesClient(this._options));
    }

    public get conferenceMembers(): ConferenceMembersClient {
        return (this._conferenceMembers ??= new ConferenceMembersClient(this._options));
    }

    public get conferenceRecording(): ConferenceRecordingClient {
        return (this._conferenceRecording ??= new ConferenceRecordingClient(this._options));
    }

    public get recordings(): RecordingsClient {
        return (this._recordings ??= new RecordingsClient(this._options));
    }

    public get credentials(): CredentialsClient {
        return (this._credentials ??= new CredentialsClient(this._options));
    }

    public get ipAccessControlList(): IpAccessControlListClient {
        return (this._ipAccessControlList ??= new IpAccessControlListClient(this._options));
    }

    public get originationUri(): OriginationUriClient {
        return (this._originationUri ??= new OriginationUriClient(this._options));
    }

    public get applications(): ApplicationsClient {
        return (this._applications ??= new ApplicationsClient(this._options));
    }

    public get endpoints(): EndpointsClient {
        return (this._endpoints ??= new EndpointsClient(this._options));
    }

    public get partnerApi(): PartnerApiClient {
        return (this._partnerApi ??= new PartnerApiClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
