// This file was auto-generated by Fern from our API Definition.

export const VobizEnvironment = {
    Production: "https://api.vobiz.ai",
} as const;

export type VobizEnvironment = typeof VobizEnvironment.Production;
