// This file was auto-generated by Fern from our API Definition.

export interface Application {
    app_id?: string | undefined;
    app_name?: string | undefined;
    application_type?: string | undefined;
    answer_url?: string | undefined;
    answer_method?: Application.AnswerMethod | undefined;
    hangup_url?: string | undefined;
    hangup_method?: Application.HangupMethod | undefined;
    fallback_answer_url?: string | undefined;
    fallback_method?: Application.FallbackMethod | undefined;
    message_url?: string | undefined;
    message_method?: Application.MessageMethod | undefined;
    default_number_app?: boolean | undefined;
    default_endpoint_app?: boolean | undefined;
    default_app?: boolean | undefined;
    enabled?: boolean | undefined;
    log_incoming_message?: boolean | undefined;
    public_uri?: boolean | undefined;
    sip_transfer_url?: string | undefined;
    sip_transfer_method?: Application.SipTransferMethod | undefined;
    sip_uri?: string | undefined;
    sub_account?: (string | null) | undefined;
    resource_uri?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}

export namespace Application {
    export const AnswerMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type AnswerMethod = (typeof AnswerMethod)[keyof typeof AnswerMethod];
    export const HangupMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type HangupMethod = (typeof HangupMethod)[keyof typeof HangupMethod];
    export const FallbackMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type FallbackMethod = (typeof FallbackMethod)[keyof typeof FallbackMethod];
    export const MessageMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type MessageMethod = (typeof MessageMethod)[keyof typeof MessageMethod];
    export const SipTransferMethod = {
        Get: "GET",
        Post: "POST",
    } as const;
    export type SipTransferMethod = (typeof SipTransferMethod)[keyof typeof SipTransferMethod];
}
