// This file was auto-generated by Fern from our API Definition.

/**
 * Result of an atomic transfer from the partner master wallet to a customer sub-account.
 */
export interface BalanceTransferResult {
    transaction_id?: string | undefined;
    customer_auth_id?: string | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    description?: string | undefined;
    partner_balance_after?: number | undefined;
    customer_balance_after?: number | undefined;
    status?: BalanceTransferResult.Status | undefined;
    created_at?: string | undefined;
}

export namespace BalanceTransferResult {
    export const Status = {
        Completed: "completed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
