// This file was auto-generated by Fern from our API Definition.

export interface Balance {
    auth_id?: string | undefined;
    balance?: string | undefined;
    currency?: string | undefined;
    auto_recharge?: boolean | undefined;
}
