// This file was auto-generated by Fern from our API Definition.

/** Account capacity to price or purchase. */
export const CapacityResourceType = {
    ConcurrentCalls: "concurrent_calls",
    Cps: "cps",
} as const;
export type CapacityResourceType = (typeof CapacityResourceType)[keyof typeof CapacityResourceType];
