// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../index.js";

export interface ChannelSubscription {
    id: string;
    account_id: number;
    resource_type: Vobiz.CapacityResourceType;
    quantity: number;
    /** Recurring monthly charge as a decimal string. */
    monthly_cost: string;
    currency: string;
    status: string;
    last_billing_date: string;
    next_billing_date: string;
    purchased_at: string;
    cancelled_at: string | null;
    cancellation_reason: string | null;
    is_active: boolean;
    created_at: string;
    updated_at: string;
}
