// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../index.js";

export interface ChannelPricingPreview {
    resource_type: Vobiz.CapacityResourceType;
    quantity: number;
    /** Calculated monthly charge as a decimal string. */
    monthly_cost: string;
    /** Currency assigned by the account's pricing tier. */
    currency: string;
    /** Pricing-bracket calculation details when supplied by the pricing tier. */
    breakdown: Record<string, unknown>[];
}
