// This file was auto-generated by Fern from our API Definition.

export interface Endpoint {
    endpoint_id?: string | undefined;
    username?: string | undefined;
    alias?: string | undefined;
    sip_uri?: string | undefined;
    sip_registered?: Endpoint.SipRegistered | undefined;
    sip_contact?: (string | null) | undefined;
    sip_expires?: (string | null) | undefined;
    sip_user_agent?: (string | null) | undefined;
    application?: (Endpoint.Application | null) | undefined;
    allow_voice?: boolean | undefined;
    allow_message?: boolean | undefined;
    allow_video?: boolean | undefined;
    allow_same_domain?: boolean | undefined;
    allow_other_domains?: boolean | undefined;
    allow_phones?: boolean | undefined;
    allow_apps?: boolean | undefined;
    sub_account?: (string | null) | undefined;
    resource_uri?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}

export namespace Endpoint {
    export const SipRegistered = {
        True: "true",
        False: "false",
    } as const;
    export type SipRegistered = (typeof SipRegistered)[keyof typeof SipRegistered];

    export interface Application {
        app_id?: string | undefined;
        app_name?: string | undefined;
        answer_url?: string | undefined;
        answer_method?: string | undefined;
    }
}
