// This file was auto-generated by Fern from our API Definition.

/**
 * Outcome of a single KYC verification step.
 */
export interface KycVerificationResult {
    verification_type: KycVerificationResult.VerificationType;
    status: KycVerificationResult.Status;
    /** Recomputed sub-account call-blocking state after this verification. */
    kyc_calls_blocked?: boolean | undefined;
    /** Present and `true` on responses from the test-mode endpoints. */
    mock?: boolean | undefined;
}

export namespace KycVerificationResult {
    export const VerificationType = {
        Pan: "pan",
        Gst: "gst",
        Cin: "cin",
        Aadhaar: "aadhaar",
    } as const;
    export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType];
    export const Status = {
        Verified: "verified",
        Failed: "failed",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
