// This file was auto-generated by Fern from our API Definition.

/**
 * A single credit or debit ledger entry on a partner or customer account.
 */
export interface PartnerTransaction {
    id?: string | undefined;
    type?: PartnerTransaction.Type | undefined;
    amount?: number | undefined;
    currency?: string | undefined;
    balance_before?: number | undefined;
    balance_after?: number | undefined;
    description?: string | undefined;
    initiated_by?: string | undefined;
    created_at?: string | undefined;
}

export namespace PartnerTransaction {
    export const Type = {
        Recharge: "recharge",
        Debit: "debit",
        Adjustment: "adjustment",
        Refund: "refund",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
