// This file was auto-generated by Fern from our API Definition.

/**
 * Call detail record for a single voice session under a partner customer account.
 */
export interface PartnerCdr {
    call_uuid?: string | undefined;
    from_number?: string | undefined;
    to_number?: string | undefined;
    direction?: PartnerCdr.Direction | undefined;
    status?: PartnerCdr.Status | undefined;
    duration_seconds?: number | undefined;
    hangup_cause?: string | undefined;
    cost?: number | undefined;
    currency?: string | undefined;
    start_time?: string | undefined;
    answer_time?: string | undefined;
    end_time?: string | undefined;
    trunk_id?: string | undefined;
    context?: string | undefined;
    account_auth_id?: string | undefined;
}

export namespace PartnerCdr {
    export const Direction = {
        Inbound: "inbound",
        Outbound: "outbound",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
    export const Status = {
        Answered: "answered",
        Busy: "busy",
        Failed: "failed",
        NoAnswer: "no-answer",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
