// This file was auto-generated by Fern from our API Definition.

/**
 * Partner identity, balance, GST configuration, and permanent partner ID.
 */
export interface PartnerProfile {
    /** Permanent partner ID - required as a filter parameter for Transaction and CDR queries. */
    id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
    company?: string | undefined;
    balance?: number | undefined;
    currency?: string | undefined;
    gstin?: string | undefined;
    gst_status?: string | undefined;
    tds_applicable?: boolean | undefined;
    tds_percentage?: number | undefined;
    account_type?: string | undefined;
    status?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}
