// This file was auto-generated by Fern from our API Definition.

/**
 * Aggregated call analytics across all customer accounts for a date range.
 */
export interface PartnerAnalytics {
    period?: PartnerAnalytics.Period | undefined;
    totals?: PartnerAnalytics.Totals | undefined;
    by_direction?: PartnerAnalytics.ByDirection | undefined;
    top_customers?: PartnerAnalytics.TopCustomers.Item[] | undefined;
}

export namespace PartnerAnalytics {
    export interface Period {
        from?: string | undefined;
        to?: string | undefined;
    }

    export interface Totals {
        total_calls?: number | undefined;
        answered_calls?: number | undefined;
        failed_calls?: number | undefined;
        total_duration_seconds?: number | undefined;
        total_cost?: number | undefined;
        currency?: string | undefined;
    }

    export interface ByDirection {
        inbound?: ByDirection.Inbound | undefined;
        outbound?: ByDirection.Outbound | undefined;
    }

    export namespace ByDirection {
        export interface Inbound {
            calls?: number | undefined;
            cost?: number | undefined;
        }

        export interface Outbound {
            calls?: number | undefined;
            cost?: number | undefined;
        }
    }

    export type TopCustomers = TopCustomers.Item[];

    export namespace TopCustomers {
        export interface Item {
            auth_id?: string | undefined;
            name?: string | undefined;
            calls?: number | undefined;
            cost?: number | undefined;
        }
    }
}
