// This file was auto-generated by Fern from our API Definition.

/**
 * A DID phone number assigned to a customer account under the partner umbrella.
 */
export interface PartnerNumber {
    number?: string | undefined;
    account_auth_id?: string | undefined;
    account_name?: string | undefined;
    number_type?: string | undefined;
    country?: string | undefined;
    region?: string | undefined;
    status?: PartnerNumber.Status | undefined;
    application_id?: string | undefined;
    application_name?: string | undefined;
    trunk_id?: string | undefined;
    monthly_cost?: number | undefined;
    currency?: string | undefined;
    assigned_at?: string | undefined;
    expires_at?: (string | null) | undefined;
}

export namespace PartnerNumber {
    export const Status = {
        Active: "active",
        Inactive: "inactive",
        Expired: "expired",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
