// This file was auto-generated by Fern from our API Definition.

/**
 * A SIP-enabled customer sub-account under your partner umbrella.
 */
export interface PartnerCustomer {
    /** Permanent customer identifier - primary key for balance transfers, CDR lookups, transaction queries, and number assignments. */
    auth_id?: string | undefined;
    name?: string | undefined;
    email?: string | undefined;
    status?: PartnerCustomer.Status | undefined;
    balance?: number | undefined;
    currency?: string | undefined;
    country?: string | undefined;
    timezone?: string | undefined;
    created_at?: string | undefined;
}

export namespace PartnerCustomer {
    export const Status = {
        Active: "active",
        Suspended: "suspended",
        Inactive: "inactive",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
