// This file was auto-generated by Fern from our API Definition.

export interface PhoneNumber {
    number?: string | undefined;
    number_type?: PhoneNumber.NumberType | undefined;
    country?: string | undefined;
    monthly_rental_rate?: string | undefined;
    status?: PhoneNumber.Status | undefined;
}

export namespace PhoneNumber {
    export const NumberType = {
        Mobile: "mobile",
        Landline: "landline",
        TollFree: "toll_free",
    } as const;
    export type NumberType = (typeof NumberType)[keyof typeof NumberType];
    export const Status = {
        Active: "active",
        Inactive: "inactive",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
