// This file was auto-generated by Fern from our API Definition.

export interface PurchasedNumber {
    id?: string | undefined;
    auth_id?: string | undefined;
    e164?: string | undefined;
    country?: string | undefined;
    region?: string | undefined;
    status?: string | undefined;
    provider?: string | undefined;
    setup_fee?: number | undefined;
    monthly_fee?: number | undefined;
    currency?: string | undefined;
    purchased_at?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}
