// This file was auto-generated by Fern from our API Definition.

export type GetConferenceResponse =
    | {
          conference_name: string;
          conference_run_time: string;
          conference_member_count: string;
          members: {
              muted?: boolean | undefined;
              member_id?: string | undefined;
              deaf?: boolean | undefined;
              from?: string | undefined;
              to?: string | undefined;
              caller_name?: string | undefined;
              direction?: string | undefined;
              call_uuid?: string | undefined;
              join_time?: string | undefined;
          }[];
          api_id: string;
      }
    | {
          error: "failed";
          api_id: string;
      };
