// This file was auto-generated by Fern from our API Definition.

export interface ListConferencesResponse {
    api_id: string;
    /** Conference names reported by the API. An empty array is inconclusive. */
    conferences: string[];
}
