// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         uri_id: "uri_id"
 *     }
 */
export interface DeleteOriginationUriRequest {
    /** Your account Auth ID */
    auth_id: string;
    uri_id: string;
}
