// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         conference_name: "conference_name",
 *         member_id: "member_id",
 *         url: "https://example.com/audio.mp3"
 *     }
 */
export interface PlayAudioMemberRequest {
    /** Your account Auth ID */
    auth_id: string;
    conference_name: string;
    member_id: string;
    /** URL of the audio file to play */
    url: string;
}
