// This file was auto-generated by Fern from our API Definition.

export interface ListIpAclsResponse {
    meta: ListIpAclsResponse.Meta;
    objects: ListIpAclsResponse.Objects.Item[];
}

export namespace ListIpAclsResponse {
    export interface Meta {
        limit: number;
        offset: number;
        total: number;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            id: string;
            account_id: string;
            ip_address: string;
            description: string;
            enabled: boolean;
            created_at: string;
            updated_at: string;
        }
    }
}
