// This file was auto-generated by Fern from our API Definition.

export interface UpdateIpAclResponse {
    id: string;
    account_id: string;
    ip_address: string;
    description: string;
    enabled: boolean;
    created_at: string;
    updated_at: string;
}
