// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         name: "Customer Co",
 *         email: "customer@example.com",
 *         password: "Customer@12345",
 *         kyc_mode: "customer_use",
 *         business_type: "private_limited"
 *     }
 */
export interface CreateSubaccountRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Human-readable name for the sub-account. */
    name: string;
    /** Required when `kyc_mode` is `customer_use`. */
    email?: string;
    /** Login password for the sub-account. */
    password?: string;
    /**
     * `personal_use` inherits parent KYC. `customer_use` requires
     * the sub-account to complete its own KYC and requires `email`.
     */
    kyc_mode?: CreateSubaccountRequest.KycMode;
    /** Legal constitution of the customer. Drives which KYC documents are required. */
    business_type?: CreateSubaccountRequest.BusinessType;
    enabled?: boolean;
}

export namespace CreateSubaccountRequest {
    /**
     * `personal_use` inherits parent KYC. `customer_use` requires
     * the sub-account to complete its own KYC and requires `email`.
     */
    export const KycMode = {
        PersonalUse: "personal_use",
        CustomerUse: "customer_use",
    } as const;
    export type KycMode = (typeof KycMode)[keyof typeof KycMode];
    /** Legal constitution of the customer. Drives which KYC documents are required. */
    export const BusinessType = {
        Individual: "individual",
        Proprietorship: "proprietorship",
        PrivateLimited: "private_limited",
        Llp: "llp",
        Partnership: "partnership",
        PublicLimited: "public_limited",
        Trust: "trust",
        Society: "society",
        Huf: "huf",
        Government: "government",
    } as const;
    export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];
}
