// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         sub_auth_id: "SA_XXXXXX"
 *     }
 */
export interface RetrieveSubaccountRequest {
    /** Your account Auth ID */
    auth_id: string;
    sub_auth_id: string;
}
