// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         sub_auth_id: "sub_auth_id",
 *         kyc_mode: "customer_use"
 *     }
 */
export interface UpdateSubaccountRequest {
    /** Your account Auth ID */
    auth_id: string;
    sub_auth_id: string;
    name?: string;
    enabled?: boolean;
    /** Change the verification mode. Promoting to `customer_use` requires the sub-account to have an `email`. */
    kyc_mode?: UpdateSubaccountRequest.KycMode;
}

export namespace UpdateSubaccountRequest {
    /** Change the verification mode. Promoting to `customer_use` requires the sub-account to have an `email`. */
    export const KycMode = {
        PersonalUse: "personal_use",
        CustomerUse: "customer_use",
    } as const;
    export type KycMode = (typeof KycMode)[keyof typeof KycMode];
}
