// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         company_name: "ACME PRIVATE LIMITED",
 *         selected_cin: "U72900KA2024PTC123456"
 *     }
 */
export interface ConfirmSubaccountCinRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    company_name: string;
    selected_cin: string;
}
