// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         account_auth_id: "SA_XXXXXX",
 *         flow_type: "email",
 *         customer_email: "customer@example.com",
 *         webhook_url: "https://your-app.example.com/kyc/webhook",
 *         expires_in_days: 30
 *     }
 *
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         account_auth_id: "SA_XXXXXX",
 *         flow_type: "redirect",
 *         redirect_url: "https://your-app.example.com/kyc/done",
 *         webhook_url: "https://your-app.example.com/kyc/webhook",
 *         expires_in_days: 30
 *     }
 */
export interface CreateSubaccountKycSessionRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    /** The sub-account's auth_id (typically equal to the path `sub_auth_id`). */
    account_auth_id: string;
    flow_type: CreateSubaccountKycSessionRequest.FlowType;
    /** Required when `flow_type` is `email`. */
    customer_email?: string;
    /**
     * Required when `flow_type` is `redirect`. After verification the customer's
     * browser is sent to this URL.
     */
    redirect_url?: string;
    /** HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent. */
    webhook_url?: string;
    expires_in_days?: number;
}

export namespace CreateSubaccountKycSessionRequest {
    export const FlowType = {
        Email: "email",
        Redirect: "redirect",
    } as const;
    export type FlowType = (typeof FlowType)[keyof typeof FlowType];
}
