// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX"
 *     }
 */
export interface GetSubaccountKycStatusRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
}
