// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         company_name: "ACME PRIVATE LIMITED"
 *     }
 */
export interface SearchSubaccountCinRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    company_name: string;
}
