// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         redirect_url: "https://partner.example.com/kyc/callback"
 *     }
 */
export interface SubaccountDigilockerInitiateRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    redirect_url: string;
    /** Opaque value echoed back on the redirect for CSRF protection. */
    oauth_state?: string;
}
