// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         access_request_id: "AR_xxxxxxxx"
 *     }
 */
export interface SubaccountDigilockerVerifyRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    access_request_id: string;
    /** Optional. Binds the Aadhaar to a specific number (92-series). */
    linked_number?: string;
}
