// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         pan: "ABCDE1234F"
 *     }
 */
export interface VerifySubaccountPanRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    pan: string;
}
