// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         gstin: "29AAJCN5983D1Z0"
 *     }
 */
export interface VerifySubaccountGstRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    gstin: string;
}
