// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         name: "My Outbound Trunk",
 *         trunk_type: "OUTBOUND",
 *         max_concurrent_calls: 10
 *     }
 */
export interface CreateTrunkRequest {
    /** Your account Auth ID */
    auth_id: string;
    name: string;
    trunk_type: string;
    max_concurrent_calls: number;
}
