// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         trunk_id: "trunk_id",
 *         name: "name",
 *         max_concurrent_calls: 1,
 *         enabled: true
 *     }
 */
export interface UpdateTrunkRequest {
    /** Your account Auth ID */
    auth_id: string;
    trunk_id: string;
    name: string;
    max_concurrent_calls: number;
    enabled: boolean;
    /** HTTPS URL for real-time call-event webhooks (`CallInitiated`, `Hangup`). See [Trunk Webhooks](/trunks/webhook). */
    webhook_url?: string;
    /** HTTP method for the webhook callback. Defaults to `POST`. */
    webhook_method?: UpdateTrunkRequest.WebhookMethod;
}

export namespace UpdateTrunkRequest {
    /** HTTP method for the webhook callback. Defaults to `POST`. */
    export const WebhookMethod = {
        Post: "POST",
        Get: "GET",
    } as const;
    export type WebhookMethod = (typeof WebhookMethod)[keyof typeof WebhookMethod];
}
