// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         trunk_id: "trunk_id",
 *         name: "name",
 *         max_concurrent_calls: 1,
 *         enabled: true
 *     }
 */
export interface UpdateTrunkRequest {
    /** Your account Auth ID */
    auth_id: string;
    trunk_id: string;
    name: string;
    max_concurrent_calls: number;
    enabled: boolean;
}
