// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         username: "john_doe",
 *         password: "SecurePassword123!",
 *         alias: "John's Desktop Phone",
 *         application: 12345678
 *     }
 */
export interface CreateEndpointRequest {
    /** Your account Auth ID */
    auth_id: string;
    username: string;
    password: string;
    alias: string;
    application: number;
}
