// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         endpoint_id: "87654321"
 *     }
 */
export interface DeleteEndpointRequest {
    /** Your account Auth ID */
    auth_id: string;
    endpoint_id: string;
}
