// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX"
 *     }
 */
export interface ListEndpointsRequest {
    /** Your account Auth ID */
    auth_id: string;
    limit?: number;
    offset?: number;
    username__contains?: string;
    username__exact?: string;
    username__startswith?: string;
    alias__contains?: string;
    alias__exact?: string;
    application_id__exact?: number;
    application_id__isnull?: boolean;
    sub_account?: string;
}
