// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         endpoint_id: "87654321",
 *         alias: "John's Updated Desktop Phone",
 *         password: "NewSecurePassword456!"
 *     }
 */
export interface UpdateEndpointRequest {
    /** Your account Auth ID */
    auth_id: string;
    endpoint_id: string;
    alias: string;
    password: string;
}
