// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         conference_name: "conference_name"
 *     }
 */
export interface StartConferenceRecordingRequest {
    /** Your account Auth ID */
    auth_id: string;
    conference_name: string;
    file_format?: StartConferenceRecordingRequest.FileFormat;
    callback_url?: string;
}

export namespace StartConferenceRecordingRequest {
    export const FileFormat = {
        Mp3: "mp3",
        Wav: "wav",
    } as const;
    export type FileFormat = (typeof FileFormat)[keyof typeof FileFormat];
}
