// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         recording_id: "recording_id"
 *     }
 */
export interface DeleteRecordingRequest {
    /** Your account Auth ID */
    auth_id: string;
    recording_id: string;
}
