// This file was auto-generated by Fern from our API Definition.

export interface ListApplicationsResponse {
    api_id: string;
    meta: ListApplicationsResponse.Meta;
    objects: ListApplicationsResponse.Objects.Item[];
}

export namespace ListApplicationsResponse {
    export interface Meta {
        limit: number;
        next: string;
        offset: number;
        previous: unknown | null;
        total_count: number;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            answer_method: string;
            answer_url: string;
            app_id: string;
            app_name: string;
            application_type: string;
            created_at: string;
            default_app: boolean;
            default_endpoint_app: boolean;
            enabled: boolean;
            fallback_answer_url: string | null;
            fallback_method: string;
            hangup_method: string;
            hangup_url: string;
            log_incoming_message: boolean;
            message_method: string;
            message_url: string | null;
            public_uri: boolean;
            resource_uri: string;
            sip_transfer_method: string;
            sip_transfer_url: unknown | null;
            sip_uri: string;
            sub_account: unknown | null;
            updated_at: string;
        }
    }
}
