// This file was auto-generated by Fern from our API Definition.

export interface GetRecordingResponse {
    add_time: string;
    api_id: string;
    call_uuid: string;
    conference_name: unknown | null;
    from_number: string;
    monthly_recording_storage_amount: number;
    recording_duration_ms: string;
    recording_end_ms: unknown | null;
    recording_format: string;
    recording_id: string;
    recording_start_ms: unknown | null;
    recording_storage_duration: number;
    recording_storage_rate: number;
    recording_type: string;
    recording_url: string;
    resource_uri: string;
    rounded_recording_duration: number;
    to_number: string;
}
