// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "call_uuid",
 *         digits: "1234",
 *         leg: "aleg"
 *     }
 */
export interface SendDtmfRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    digits: string;
    leg?: SendDtmfRequest.Leg;
}

export namespace SendDtmfRequest {
    export const Leg = {
        Aleg: "aleg",
        Bleg: "bleg",
        Both: "both",
    } as const;
    export type Leg = (typeof Leg)[keyof typeof Leg];
}
