// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         gstin: "TESTSUCCESS0001GST"
 *     }
 */
export interface MockVerifySubaccountGstRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    gstin: string;
}
