// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         access_request_id: "MOCK_AR_SUCCESS"
 *     }
 */
export interface MockSubaccountDigilockerVerifyRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    access_request_id: MockSubaccountDigilockerVerifyRequest.AccessRequestId;
}

export namespace MockSubaccountDigilockerVerifyRequest {
    export const AccessRequestId = {
        MockArSuccess: "MOCK_AR_SUCCESS",
        MockArFail: "MOCK_AR_FAIL",
    } as const;
    export type AccessRequestId = (typeof AccessRequestId)[keyof typeof AccessRequestId];
}
