// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         sub_auth_id: "SA_XXXXXX",
 *         verification_type: "pan",
 *         outcome: "verified"
 *     }
 */
export interface MockFinalizePendingKycRequest {
    /** The sub-account's Auth ID. */
    sub_auth_id: string;
    verification_type: MockFinalizePendingKycRequest.VerificationType;
    outcome: MockFinalizePendingKycRequest.Outcome;
}

export namespace MockFinalizePendingKycRequest {
    export const VerificationType = {
        Pan: "pan",
        Aadhaar: "aadhaar",
        Gst: "gst",
        Cin: "cin",
    } as const;
    export type VerificationType = (typeof VerificationType)[keyof typeof VerificationType];
    export const Outcome = {
        Verified: "verified",
        Failed: "failed",
    } as const;
    export type Outcome = (typeof Outcome)[keyof typeof Outcome];
}
