// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         from: "14155551234",
 *         to: "+919876543210",
 *         answer_url: "https://example.com/answer",
 *         answer_method: "POST"
 *     }
 */
export interface MakeCallRequest {
    /** Your account Auth ID */
    auth_id: string;
    from: string;
    to: string;
    answer_url: string;
    answer_method: string;
}
