// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         recipient: {
 *             customer_account: ["admin@example.com"]
 *         },
 *         from: "2025-01-23 00:00:00",
 *         to: "2025-01-30 23:59:59"
 *     }
 *
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         recipient: {
 *             customer_account: ["admin@example.com"]
 *         },
 *         recording_storage_duration: "7"
 *     }
 *
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         recipient: {
 *             customer_account: ["admin@example.com"]
 *         },
 *         recording_storage_duration__gte: "7",
 *         recording_storage_duration__lte: "30"
 *     }
 *
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         recipient: {
 *             customer_account: ["admin@example.com", "backup@example.com"]
 *         },
 *         from: "2025-01-01 00:00:00",
 *         to: "2025-01-30 23:59:59",
 *         conference_name: "TeamMeeting",
 *         recording_format: "mp3"
 *     }
 */
export interface BulkExportRecordingsRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Email delivery targets for the export archive. */
    recipient: BulkExportRecordingsRequest.Recipient;
    /** Start date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to 7 days ago. */
    from?: string;
    /** End date for the export. Format: YYYY-MM-DD HH:MM:SS. Defaults to the current time. */
    to?: string;
    /** Export recordings exactly N days old. `"7"` exports recordings from exactly 7 days ago. */
    recording_storage_duration?: string;
    /** Export recordings N days old or older. `"7"` exports recordings 7 days old and older. */
    recording_storage_duration__gte?: string;
    /** Export recordings older than N days. `"7"` exports recordings 8 days old and older. */
    recording_storage_duration__gt?: string;
    /** Export recordings N days old or newer. `"30"` exports recordings 0-30 days old. */
    recording_storage_duration__lte?: string;
    /** Export recordings newer than N days. `"30"` exports recordings 0-29 days old. */
    recording_storage_duration__lt?: string;
    /** Filter by caller phone number. Applies when the range is 30 days or less. */
    from_number?: string;
    /** Filter by destination phone number. Applies when the range is 30 days or less. */
    to_number?: string;
    /** Filter by call UUID. Also use this field for a conference_uuid or mpc_uuid. Applies when the range is 30 days or less. */
    call_uuid?: string;
    /** Filter by conference name. Also use this field for an mpc_name. Applies when the range is 30 days or less. */
    conference_name?: string;
    /** Filter by recording format. Applies when the range is 30 days or less. */
    recording_format?: BulkExportRecordingsRequest.RecordingFormat;
    /** Filter by a specific recording ID. Applies when the range is 30 days or less. */
    recording_id?: string;
}

export namespace BulkExportRecordingsRequest {
    /**
     * Email delivery targets for the export archive.
     */
    export interface Recipient {
        /** Email addresses that receive the download link. All addresses must be in valid format. */
        customer_account: string[];
    }

    /** Filter by recording format. Applies when the range is 30 days or less. */
    export const RecordingFormat = {
        Mp3: "mp3",
        Wav: "wav",
    } as const;
    export type RecordingFormat = (typeof RecordingFormat)[keyof typeof RecordingFormat];
}
