// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         credential_id: "credential_id",
 *         password: "password"
 *     }
 */
export interface UpdateCredentialRequest {
    /** Your account Auth ID */
    auth_id: string;
    credential_id: string;
    password: string;
}
