// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "cdr_XXXXXXXXXX",
 *         time_limit: 120,
 *         file_format: "mp3"
 *     }
 */
export interface StartRecordingRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    time_limit?: number;
    file_format?: StartRecordingRequest.FileFormat;
    /** Set to `auto` to enable transcription */
    transcription_type?: string;
    callback_url?: string;
    record_channel_type?: StartRecordingRequest.RecordChannelType;
}

export namespace StartRecordingRequest {
    export const FileFormat = {
        Mp3: "mp3",
        Wav: "wav",
    } as const;
    export type FileFormat = (typeof FileFormat)[keyof typeof FileFormat];
    export const RecordChannelType = {
        Mono: "mono",
        Stereo: "stereo",
    } as const;
    export type RecordChannelType = (typeof RecordChannelType)[keyof typeof RecordChannelType];
}
