// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "John Doe",
 *         email: "john@example.com",
 *         phone: "+919876543210",
 *         password: "SecurePass123!",
 *         country: "IN"
 *     }
 */
export interface CreateCustomerAccountRequest {
    /** Customer's full name. */
    name: string;
    /** Customer's email. KYC link is sent here. */
    email: string;
    /** E.164 format. */
    phone: string;
    /** Min 8 chars, must include a number and a special character. */
    password: string;
    /** Legal company or business name. */
    company?: string;
    /** ISO 2-letter country code. */
    country: string;
}
