// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListKycSessionsRequest {
    status?: Vobiz.ListKycSessionsRequestStatus;
    account_auth_id?: string;
    page?: number;
    size?: number;
}
