// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         customer_auth_id: "customer_auth_id",
 *         hangup_cause: "NO_ANSWER"
 *     }
 */
export interface ListCustomerCdrsRequest {
    customer_auth_id: string;
    start_date?: string;
    end_date?: string;
    call_direction?: Vobiz.ListCustomerCdrsRequestCallDirection;
    status?: Vobiz.ListCustomerCdrsRequestStatus;
    min_duration?: number;
    hangup_cause?: string;
    per_page?: number;
}
