// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         customer_auth_id: "customer_auth_id",
 *         from_date: "2026-03-01",
 *         to_date: "2026-03-31"
 *     }
 */
export interface ListCustomerTransactionsRequest {
    customer_auth_id: string;
    from_date?: string;
    to_date?: string;
    transaction_type?: Vobiz.ListCustomerTransactionsRequestTransactionType;
    page?: number;
    per_page?: number;
}
