// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListCustomerAccountsRequest {
    page?: number;
    per_page?: number;
    /** Substring match on name or email. */
    search?: string;
}
