// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         customer_auth_id: "customer_auth_id"
 *     }
 */
export interface ListCustomerNumbersRequest {
    customer_auth_id: string;
    /** Substring match against the E.164 number. */
    search?: string;
    page?: number;
    per_page?: number;
}
