// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         customer_auth_id: "MA_ZKITB8Z2",
 *         amount: 500,
 *         currency: "INR"
 *     }
 */
export interface PartnerTransferBalanceRequest {
    customer_auth_id: string;
    /** Positive decimal. Your master balance must be ≥ this amount. */
    amount: number;
    /** Must match your partner account currency. */
    currency: string;
    /** Note for your records. Appears in both ledgers. */
    description?: string;
}
