// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         session_id: "session_id"
 *     }
 */
export interface RevokeKycSessionRequest {
    session_id: string;
    reason?: string;
}
