// This file was auto-generated by Fern from our API Definition.

export interface CreateOriginationUriResponse {
    id: string;
    account_id: string;
    uri: string;
    priority: number;
    weight: number;
    enabled: boolean;
    transport: string;
    description: string;
    created_at: string;
    updated_at: string;
}
