// This file was auto-generated by Fern from our API Definition.

export interface ListOriginationUrisResponse {
    meta: ListOriginationUrisResponse.Meta;
    objects: ListOriginationUrisResponse.Objects.Item[];
}

export namespace ListOriginationUrisResponse {
    export interface Meta {
        limit: number;
        offset: number;
        total: number;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            id: string;
            account_id: string;
            uri: string;
            priority: number;
            weight: number;
            enabled: boolean;
            transport: string;
            description: string;
            created_at: string;
            updated_at: string;
        }
    }
}
