// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXX",
 *         resource_type: "concurrent_calls",
 *         quantity: 30
 *     }
 */
export interface PreviewChannelPricingRequest {
    /** Target account Auth ID. An account can preview only its own pricing; administrators may act for another account. */
    auth_id: string;
    /** Capacity type to price. */
    resource_type: Vobiz.CapacityResourceType;
    /** Capacity quantity to price. Pricing-tier block and quantity rules also apply. */
    quantity: number;
}
