// This file was auto-generated by Fern from our API Definition.

export interface CancelNumberReleaseResponse {
    message: string;
    status: CancelNumberReleaseResponse.Status;
    refund_status: CancelNumberReleaseResponse.RefundStatus;
    /** Present when the refund could not be processed. */
    refund_error?: string | undefined;
}

export namespace CancelNumberReleaseResponse {
    export const Status = {
        Active: "active",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const RefundStatus = {
        Success: "success",
        Failed: "failed",
    } as const;
    export type RefundStatus = (typeof RefundStatus)[keyof typeof RefundStatus];
}
