// This file was auto-generated by Fern from our API Definition.

export interface GetNumberHealthResponse {
    e164?: string | undefined;
    status?: string | undefined;
    /** Reputation/usage rating for the number. */
    usage_status?: string | undefined;
    is_spam?: boolean | undefined;
    granularity?: string | undefined;
    summary?: GetNumberHealthResponse.Summary | undefined;
    snapshots?: GetNumberHealthResponse.Snapshots.Item[] | undefined;
}

export namespace GetNumberHealthResponse {
    export interface Summary {
        period_days?: number | undefined;
        total_calls?: number | undefined;
        answered_calls?: number | undefined;
        answer_rate?: number | undefined;
        total_minutes?: number | undefined;
        avg_duration?: number | undefined;
    }

    export type Snapshots = Snapshots.Item[];

    export namespace Snapshots {
        export interface Item {
            id?: string | undefined;
            ts?: string | undefined;
            total_calls?: number | undefined;
            answered_calls?: number | undefined;
            failed_calls?: number | undefined;
            answer_rate?: number | undefined;
            total_duration?: number | undefined;
            avg_duration?: number | undefined;
            total_minutes?: number | undefined;
        }
    }
}
