// This file was auto-generated by Fern from our API Definition.

export const GetNumberHealthRequestGranularity = {
    Daily: "daily",
    Hourly: "hourly",
} as const;
export type GetNumberHealthRequestGranularity =
    (typeof GetNumberHealthRequestGranularity)[keyof typeof GetNumberHealthRequestGranularity];
