// This file was auto-generated by Fern from our API Definition.

export interface ListNumbersResponse {
    items: ListNumbersResponse.Items.Item[];
    page: number;
    per_page: number;
    total: number;
}

export namespace ListNumbersResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            account_id: string;
            e164: string;
            country: string;
            region: string;
            capabilities: Item.Capabilities;
            status: string;
            provider: string;
            setup_fee: number;
            monthly_fee: number;
            currency: string;
            application_id?: string | undefined;
            voice_enabled: boolean;
            tags: string[];
            purchased_at: string;
            is_blocked: boolean;
            created_at: string;
            updated_at: string;
            is_trial_number: boolean;
            last_billing_date?: string | undefined;
            next_billing_date?: string | undefined;
            minimum_commitment_months: number;
            aadhaar_verification_required: boolean;
            aadhaar_verified: boolean;
            source: string;
            released_at?: string | undefined;
            trunk_group_id?: string | undefined;
        }

        export namespace Item {
            export interface Capabilities {
                voice: boolean;
                sms: boolean;
                mms: boolean;
                fax: boolean;
            }
        }
    }
}
