// This file was auto-generated by Fern from our API Definition.

export interface ListInventoryNumbersResponse {
    items: ListInventoryNumbersResponse.Items.Item[];
    page: number;
    per_page: number;
    total: number;
}

export namespace ListInventoryNumbersResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            account_id: string;
            e164: string;
            country: string;
            capabilities: Item.Capabilities;
            status: string;
            provider: string;
            setup_fee: number;
            monthly_fee: number;
            currency: string;
            voice_enabled: boolean;
            tags: unknown | null;
            is_blocked: boolean;
            created_at: string;
            updated_at: string;
            is_trial_number: boolean;
            minimum_commitment_months: number;
            aadhaar_verification_required: boolean;
            aadhaar_verified: boolean;
            region?: string | undefined;
        }

        export namespace Item {
            export interface Capabilities {
                voice: boolean;
                sms: boolean;
                mms: boolean;
                fax: boolean;
            }
        }
    }
}
