// This file was auto-generated by Fern from our API Definition.

export interface UnrentNumberResponse {
    cancel_url: string;
    cooldown_ends_at: string;
    message: string;
    note?: string | undefined;
    release_fee: number;
    status: string;
}
