// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "call_uuid",
 *         urls: "https://example.com/audio.mp3",
 *         legs: "aleg"
 *     }
 */
export interface PlayAudioCallRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    urls: string;
    legs?: PlayAudioCallRequest.Legs;
    loop?: boolean;
}

export namespace PlayAudioCallRequest {
    export const Legs = {
        Aleg: "aleg",
        Bleg: "bleg",
        Both: "both",
    } as const;
    export type Legs = (typeof Legs)[keyof typeof Legs];
}
