// This file was auto-generated by Fern from our API Definition.

export interface CreateSubaccountResponse {
    message: string;
    sub_account: CreateSubaccountResponse.SubAccount;
    auth_credentials: CreateSubaccountResponse.AuthCredentials;
    tokens: CreateSubaccountResponse.Tokens;
}

export namespace CreateSubaccountResponse {
    export interface SubAccount {
        name: string;
        email: unknown | null;
        phone: unknown | null;
        description: unknown | null;
        permissions: unknown | null;
        rate_limit: number;
        id: string;
        parent_account_id: string;
        parent_auth_id: string;
        auth_id: string;
        auth_token: string;
        api_id: string;
        email_verified: boolean;
        enabled: boolean;
        created: string;
        modified: string;
        is_active: boolean;
        created_at: string;
        updated_at: string;
        last_used: unknown | null;
        account: string;
        resource_uri: string;
    }

    export interface AuthCredentials {
        auth_id: string;
        auth_token: string;
    }

    export interface Tokens {
        access_token: string;
        refresh_token: string;
        token_type: string;
        expires_in: number;
    }
}
