// This file was auto-generated by Fern from our API Definition.

export interface ListSubaccountsResponse {
    sub_accounts: ListSubaccountsResponse.SubAccounts.Item[];
    total: number;
    page: number;
    size: number;
}

export namespace ListSubaccountsResponse {
    export type SubAccounts = SubAccounts.Item[];

    export namespace SubAccounts {
        export interface Item {
            name: string;
            email: string | null;
            phone: unknown | null;
            description: unknown | null;
            permissions: Item.Permissions;
            rate_limit: number;
            id: string;
            parent_account_id: string;
            parent_auth_id: string;
            auth_id: string;
            auth_token: string;
            api_id: string;
            email_verified: boolean;
            enabled: boolean;
            created: string;
            modified: string;
            is_active: boolean;
            created_at: string;
            updated_at: string;
            last_used: string | null;
            account: string;
            resource_uri: string;
        }

        export namespace Item {
            export type Permissions =
                | unknown
                | null
                | {
                      cdr?: boolean | undefined;
                      calls?: boolean | undefined;
                  };
        }
    }
}
