// This file was auto-generated by Fern from our API Definition.

export interface UpdateSubaccountResponse {
    name: string;
    email: unknown | null;
    phone: unknown | null;
    description: unknown | null;
    permissions: unknown | null;
    rate_limit: number;
    id: string;
    parent_account_id: string;
    parent_auth_id: string;
    auth_id: string;
    auth_token: string;
    api_id: string;
    email_verified: boolean;
    enabled: boolean;
    created: string;
    modified: string;
    is_active: boolean;
    created_at: string;
    updated_at: string;
    last_used: unknown | null;
    account: string;
    resource_uri: string;
}
