// This file was auto-generated by Fern from our API Definition.

export interface ListTrunksResponse {
    meta: ListTrunksResponse.Meta;
    objects: ListTrunksResponse.Objects.Item[];
}

export namespace ListTrunksResponse {
    export interface Meta {
        limit: number;
        offset: number;
        total: number;
    }

    export type Objects = Objects.Item[];

    export namespace Objects {
        export interface Item {
            trunk_id: string;
            account_id: string;
            name: string;
            trunk_domain: string;
            trunk_status: string;
            secure: boolean;
            trunk_direction: string;
            concurrent_calls_limit: number;
            cps_limit: number;
            credential_uuid?: string | undefined;
            description: string;
            transport: string;
            recording: boolean;
            enable_transcription: boolean;
            pii_redaction: boolean;
            webhook_method: string;
            recording_webhook_enabled: boolean;
            created_at: string;
            updated_at: string;
            primary_uri_uuid?: string | undefined;
            inbound_destination?: string | undefined;
            pii_entity_types?: string | undefined;
            webhook_url?: string | undefined;
        }
    }
}
