// This file was auto-generated by Fern from our API Definition.

export interface UpdateTrunkResponse {
    trunk_id: string;
    account_id: string;
    name: string;
    trunk_domain: string;
    trunk_status: string;
    secure: boolean;
    trunk_direction: string;
    concurrent_calls_limit: number;
    cps_limit: number;
    description: string;
    transport: string;
    recording: boolean;
    enable_transcription: boolean;
    pii_redaction: boolean;
    webhook_method: string;
    recording_webhook_enabled: boolean;
    created_at: string;
    updated_at: string;
}
