// This file was auto-generated by Fern from our API Definition.

export const ExportCdrsRequestCallDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
export type ExportCdrsRequestCallDirection =
    (typeof ExportCdrsRequestCallDirection)[keyof typeof ExportCdrsRequestCallDirection];
