// This file was auto-generated by Fern from our API Definition.

export interface ListRecentCdrsResponse {
    account_id: string;
    count: number;
    data: ListRecentCdrsResponse.Data.Item[];
    success: boolean;
}

export namespace ListRecentCdrsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            account_id: string;
            answer_time: string | null;
            billsec: number;
            bridge_uuid: string | null;
            call_direction: string;
            caller_id_name: string;
            caller_id_number: string;
            campaign_id: unknown | null;
            carrier_ip: unknown | null;
            codec: string | null;
            context: string;
            cost: number;
            created_at: string;
            currency: string;
            customer_endpoint: unknown | null;
            destination_number: string;
            duration: number;
            end_time: string;
            failure_code: string | null;
            failure_reason: string | null;
            hangup_cause: string | null;
            hangup_cause_code: number | null;
            hangup_cause_name: string | null;
            hangup_disposition: string | null;
            hangup_source: string | null;
            id: number;
            jitter: number | null;
            mos: number | null;
            network_addr: string | null;
            origination_region: string;
            packet_loss: number | null;
            progress_time: string | null;
            region: string;
            ring_time: number;
            sip_call_id: string;
            sip_user_agent: string | null;
            start_time: string;
            streaming_cost: number;
            terminated_to: string | null;
            total_cost: number;
            trunk_id: string | null;
            updated_at: string;
            uuid: string;
        }
    }
}
