// This file was auto-generated by Fern from our API Definition.

export const GetQueuedCallRequestStatus = {
    Live: "live",
    Queued: "queued",
} as const;
export type GetQueuedCallRequestStatus = (typeof GetQueuedCallRequestStatus)[keyof typeof GetQueuedCallRequestStatus];
