// This file was auto-generated by Fern from our API Definition.

export const ListQueuedCallsRequestStatus = {
    Live: "live",
    Queued: "queued",
} as const;
export type ListQueuedCallsRequestStatus =
    (typeof ListQueuedCallsRequestStatus)[keyof typeof ListQueuedCallsRequestStatus];
