// This file was auto-generated by Fern from our API Definition.

export interface ListLiveCallsResponse {
    /** Unique identifier for this API request */
    api_id: string;
    /** Array of call UUIDs for all active calls */
    calls: string[];
}
