// This file was auto-generated by Fern from our API Definition.

export const ListLiveCallsRequestStatus = {
    Live: "live",
    Queued: "queued",
} as const;
export type ListLiveCallsRequestStatus = (typeof ListLiveCallsRequestStatus)[keyof typeof ListLiveCallsRequestStatus];
