// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         name: "Office IP",
 *         ip_address: "ip_address"
 *     }
 */
export interface CreateIpAclRequest {
    /** Your account Auth ID */
    auth_id: string;
    name: string;
    ip_address: string;
}
