// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         ip_acl_id: "ip_acl_id"
 *     }
 */
export interface DeleteIpAclRequest {
    /** Your account Auth ID */
    auth_id: string;
    ip_acl_id: string;
}
