// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         app_name: "My Voice Application",
 *         answer_url: "https://example.com/answer",
 *         answer_method: "POST"
 *     }
 */
export interface CreateApplicationRequest {
    /** Your account Auth ID */
    auth_id: string;
    app_name: string;
    answer_url: string;
    answer_method: string;
}
