// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         app_id: "12345678"
 *     }
 */
export interface RetrieveApplicationRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Unique identifier for the application */
    app_id: string;
}
