// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         app_id: "12345678",
 *         app_name: "Updated Application Name",
 *         default_number_app: true
 *     }
 */
export interface UpdateApplicationRequest {
    /** Your account Auth ID */
    auth_id: string;
    app_id: string;
    app_name: string;
    default_number_app: boolean;
}
