// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         phone_number: "%2B912271264217",
 *         trunk_group_id: "e3e55a78-1234-5678-90ab-cdef12345678"
 *     }
 */
export interface AssignNumberToTrunkRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The phone number to assign, URL-encoded (use %2B instead of +). */
    phone_number: string;
    /** The UUID of the trunk to assign this number to. */
    trunk_group_id: string;
}
