// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "%2B919876543210",
 *         sub_account_id: "SA_XXXXXX"
 *     }
 */
export interface AssignDidToSubaccountRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The number in E.164, URL-encoded (use %2B instead of +). */
    e164: string;
    sub_account_id: string;
}
