// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "%2B919876543210",
 *         days: 30
 *     }
 */
export interface GetNumberHealthRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The number in E.164, URL-encoded (use %2B instead of +). */
    e164: string;
    /** Snapshot granularity. */
    granularity?: Vobiz.GetNumberHealthRequestGranularity;
    /** Size of the window (in days) for the summary and snapshots. */
    days?: number;
}
