// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         country: "IN"
 *     }
 */
export interface ListInventoryNumbersRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Filter by country code (e.g., "US", "IN"). */
    country?: string;
    /** Substring match against the E.164 number (e.g., "80" matches "+918065..."). */
    search?: string;
    page?: number;
    per_page?: number;
}
