// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         country: "IN",
 *         exclude: "9180,9192"
 *     }
 */
export interface ListInventoryNumbersRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Filter by country code (e.g., "US", "IN"). */
    country?: string;
    /** Substring match against the E.164 number (e.g., "80" matches "+918065..."). */
    search?: string;
    /** One or more E.164 prefixes to remove from results. Include the country code (e.g. "9180" for India +91 80-series, "1415" for US +1 415); a leading "+" is optional. Matched against the full E.164 form, so it works for any country. Accepts a comma-separated list ("9180,9192") or repeated params ("exclude=9180&exclude=9192"), and the two forms can be combined. It is ANDed with all other filters, so it takes priority over `search`; duplicates are de-duplicated silently and `total` reflects the filtered result set. */
    exclude?: string;
    page?: number;
    per_page?: number;
}
