// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "+919876543210",
 *         currency: "USD"
 *     }
 */
export interface PurchaseFromInventoryRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Phone number to purchase in E.164 format. */
    e164: string;
    /** Currency for transaction. Defaults to the number's currency or "USD". */
    currency?: string;
}
