// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "%2B919876543210",
 *         force: true
 *     }
 */
export interface UnassignDidFromSubaccountRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The number in E.164, URL-encoded (use %2B instead of +). */
    e164: string;
    /**
     * Admin-only cool-off bypass. Requires an admin-role account
     * (enforced at the gateway) and writes a `did_assignment_audit` row.
     */
    force?: boolean;
}
