// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         phone_number: "%2B912271264217"
 *     }
 */
export interface UnassignNumberFromTrunkRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The phone number to unassign, URL-encoded (use %2B instead of +). */
    phone_number: string;
}
