// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "919876543210"
 *     }
 */
export interface UnrentNumberRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** Phone number in E.164 format (without the +) */
    e164: string;
}
