// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         e164: "%2B919876543210"
 *     }
 */
export interface UnrentNumberRequest {
    /** Your account Auth ID */
    auth_id: string;
    /** The URL-encoded phone number in E.164 format. Encode `+` as `%2B`. */
    e164: string;
    /** Skip the 24-hour cooldown and release the number immediately. */
    immediate?: boolean;
}
