// This file was auto-generated by Fern from our API Definition.

export interface GetPartnerDashboardResponse {
    partner: GetPartnerDashboardResponse.Partner;
    period: GetPartnerDashboardResponse.Period;
    accounts: GetPartnerDashboardResponse.Accounts;
    total_balance: string;
    currency: string;
    calls: GetPartnerDashboardResponse.Calls;
    traffic: GetPartnerDashboardResponse.Traffic;
    by_product: GetPartnerDashboardResponse.ByProduct;
    time_series: GetPartnerDashboardResponse.TimeSeries.Item[];
}

export namespace GetPartnerDashboardResponse {
    export interface Partner {
        id: string;
        account_id: number;
        name: string;
        slug: string;
        company: string;
        auth_id: string;
        email: string;
        phone: string;
        billing_model: string;
        is_active: boolean;
        is_verified: boolean;
        max_accounts: number;
        can_create_accounts: boolean;
        can_create_pricing_tiers: boolean;
        can_view_cdrs: boolean;
        can_transfer_balance: boolean;
        default_pricing_tier_id: string;
        account_count: number;
        balance: unknown | null;
        created_at: string;
        updated_at: string;
    }

    export interface Period {
        from: string;
        to: string;
    }

    export interface Accounts {
        total: number;
        active: number;
        customers: Accounts.Customers.Item[];
    }

    export namespace Accounts {
        export type Customers = Customers.Item[];

        export namespace Customers {
            export interface Item {
                auth_id: string;
                name: string;
                email: string;
                phone: string;
                is_active: boolean;
                created_at: string;
            }
        }
    }

    export interface Calls {
        total_calls: number;
        answered_calls: number;
        total_minutes: number;
        total_cost: string;
    }

    export interface Traffic {
        inbound: Traffic.Inbound;
        outbound: Traffic.Outbound;
    }

    export namespace Traffic {
        export interface Inbound {
            total_calls: number;
            answered_calls: number;
            total_minutes: number;
            total_cost: string;
        }

        export interface Outbound {
            total_calls: number;
            answered_calls: number;
            total_minutes: number;
            total_cost: string;
        }
    }

    export interface ByProduct {
        sip_trunking: ByProduct.SipTrunking;
        voice_api: ByProduct.VoiceApi;
    }

    export namespace ByProduct {
        export interface SipTrunking {
            total_calls: number;
            answered_calls: number;
            total_minutes: number;
            total_cost: string;
        }

        export interface VoiceApi {
            total_calls: number;
            answered_calls: number;
            total_minutes: number;
            total_cost: string;
        }
    }

    export type TimeSeries = TimeSeries.Item[];

    export namespace TimeSeries {
        export interface Item {
            date: string;
            total_calls: number;
            answered_calls: number;
            total_minutes: number;
            total_cost: string;
            inbound: Item.Inbound;
            outbound: Item.Outbound;
        }

        export namespace Item {
            export interface Inbound {
                total_calls: number;
                answered_calls: number;
                total_minutes: number;
            }

            export interface Outbound {
                total_calls: number;
                answered_calls: number;
                total_minutes: number;
            }
        }
    }
}
