// This file was auto-generated by Fern from our API Definition.

export interface GetPartnerProfileResponse {
    id: string;
    account_id: number;
    name: string;
    slug: string;
    company: string;
    auth_id: string;
    email: string;
    phone: string;
    billing_model: string;
    is_active: boolean;
    is_verified: boolean;
    max_accounts: number;
    can_create_accounts: boolean;
    can_create_pricing_tiers: boolean;
    can_view_cdrs: boolean;
    can_transfer_balance: boolean;
    default_pricing_tier_id: string;
    account_count: number;
    balance: string;
    created_at: string;
    updated_at: string;
}
