// This file was auto-generated by Fern from our API Definition.

export interface ListCustomerCdrsResponse {
    account_id: string;
    count: number;
    data: unknown[];
    pagination: ListCustomerCdrsResponse.Pagination;
    success: boolean;
    summary: ListCustomerCdrsResponse.Summary;
    account_auth_id: string;
}

export namespace ListCustomerCdrsResponse {
    export interface Pagination {
        page: number;
        per_page: number;
        total: number;
        pages: number;
        has_next: boolean;
        has_prev: boolean;
    }

    export interface Summary {
        answerRate: number;
        answeredCalls: number;
        avgCallDuration: string;
        last_call_at: string;
        totalCalls: number;
        total_billable_seconds: number;
        total_cost: number;
        total_duration_seconds: number;
    }
}
