// This file was auto-generated by Fern from our API Definition.

export const ListCustomerCdrsRequestStatus = {
    Answered: "answered",
    Failed: "failed",
    Busy: "busy",
    NoAnswer: "no_answer",
} as const;
export type ListCustomerCdrsRequestStatus =
    (typeof ListCustomerCdrsRequestStatus)[keyof typeof ListCustomerCdrsRequestStatus];
