// This file was auto-generated by Fern from our API Definition.

export const ListCustomerCdrsRequestCallDirection = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
export type ListCustomerCdrsRequestCallDirection =
    (typeof ListCustomerCdrsRequestCallDirection)[keyof typeof ListCustomerCdrsRequestCallDirection];
