// This file was auto-generated by Fern from our API Definition.

export interface ListCustomerTransactionsResponse {
    transactions: ListCustomerTransactionsResponse.Transactions.Item[];
    summary: ListCustomerTransactionsResponse.Summary;
    total: number;
    page: number;
    per_page: number;
    total_pages: number;
    account_auth_id: string;
}

export namespace ListCustomerTransactionsResponse {
    export type Transactions = Transactions.Item[];

    export namespace Transactions {
        export interface Item {
            id: string;
            account_id: string;
            balance_id: string;
            type: string;
            amount: number;
            currency: string;
            description: string;
            reference: string;
            status: string;
            processed_at: string;
            created_at: string;
            updated_at: string;
        }
    }

    export interface Summary {
        total_transactions: number;
        total_debit: number;
        total_credit: number;
        net_amount: number;
        by_reference_type: Summary.ByReferenceType.Item[];
    }

    export namespace Summary {
        export type ByReferenceType = ByReferenceType.Item[];

        export namespace ByReferenceType {
            export interface Item {
                reference_type: string;
                total_debit: number;
                total_credit: number;
                count: number;
            }
        }
    }
}
