// This file was auto-generated by Fern from our API Definition.

export const ListKycSessionsRequestStatus = {
    EmailSent: "email_sent",
    LinkReady: "link_ready",
    Opened: "opened",
    InProgress: "in_progress",
    KycCompleted: "kyc_completed",
    Revoked: "revoked",
} as const;
export type ListKycSessionsRequestStatus =
    (typeof ListKycSessionsRequestStatus)[keyof typeof ListKycSessionsRequestStatus];
