// This file was auto-generated by Fern from our API Definition.

export interface ListKycSessionsResponse {
    sessions: ListKycSessionsResponse.Sessions.Item[];
    total: number;
    page: number;
    size: number;
}

export namespace ListKycSessionsResponse {
    export type Sessions = Sessions.Item[];

    export namespace Sessions {
        export interface Item {
            id: string;
            account_auth_id: string;
            customer_email: string | null;
            kyc_type: string | null;
            status: string;
            expires_at: string;
            first_opened_at: string | null;
            completed_at: string | null;
            webhook_url: string | null;
            redirect_url: string | null;
            reminder_schedule: Item.ReminderSchedule.Item[];
            metadata: Item.Metadata;
            verified_data: Item.VerifiedData;
            created_at: string;
            updated_at: string;
        }

        export namespace Item {
            export type ReminderSchedule = ReminderSchedule.Item[];

            export namespace ReminderSchedule {
                export interface Item {
                    value: number;
                    trigger: string;
                }
            }

            export type Metadata =
                | unknown
                | null
                | {
                      plan: string;
                      customer_ref: string;
                  };
            export type VerifiedData =
                | unknown
                | null
                | {
                      pan_type?: string | undefined;
                      pan_number?: string | undefined;
                      pan_name_match?: boolean | undefined;
                      completed_steps?: string[] | undefined;
                      pan_registered_name?: string | undefined;
                      gender?: string | undefined;
                      address?: string | undefined;
                      aadhaar_dob?: string | undefined;
                      aadhaar_name?: string | undefined;
                      masked_aadhaar?: string | undefined;
                      pan_name?: string | undefined;
                  };
        }
    }
}
