// This file was auto-generated by Fern from our API Definition.

export interface ListCustomerAccountsResponse {
    accounts: ListCustomerAccountsResponse.Accounts.Item[];
    total: number;
    page: number;
    size: number;
}

export namespace ListCustomerAccountsResponse {
    export type Accounts = Accounts.Item[];

    export namespace Accounts {
        export interface Item {
            name: string;
            email: string;
            phone: string;
            description: string | null;
            gstin: string | null;
            gst_status: string | null;
            tds_enabled: boolean;
            tds_percentage: number;
            business_type: string;
            id: string;
            auth_id: string;
            api_id: string;
            account_type: string;
            role: string;
            postpaid: boolean;
            address: string | null;
            city: string | null;
            state: string | null;
            timezone: string | null;
            country: string;
            zip_code: string | null;
            company: string;
            billing_mode: string;
            auto_recharge: boolean;
            cash_credits: string;
            cps_limit: number;
            concurrent_calls_limit: number;
            base_cps_limit: unknown | null;
            base_concurrent_calls_limit: unknown | null;
            purchased_cps: unknown | null;
            purchased_concurrent_calls: unknown | null;
            is_active: boolean;
            is_verified: boolean;
            is_trial_account: boolean;
            enabled: boolean;
            kyc_status: string;
            google_id: unknown | null;
            referral_code: string | null;
            referral_disabled: boolean;
            custom_referrer_reward_amount: unknown | null;
            custom_referee_reward_amount: unknown | null;
            created_at: string;
            updated_at: string;
            last_login: string | null;
            pricing_tier_id: string;
            pricing_tier: Item.PricingTier;
            partner_id: string;
            auto_recharge_config: unknown | null;
            resource_uri: string;
            auth_token: string;
        }

        export namespace Item {
            export interface PricingTier {
                id: string;
                name: string;
                currency: string;
                rate_per_minute: number;
                streaming_rate_per_minute: number;
                recording_rate_per_minute: number;
                whatsapp_voice_rate: number;
                transcription_rate_per_minute: number;
                pii_redaction_rate_per_minute: number;
                charge_non_connected_calls: boolean;
                non_connected_call_fee: number;
                did_release_fee: number;
                is_active: boolean;
                is_default: boolean;
                partner_id: unknown | null;
            }
        }
    }
}
