// This file was auto-generated by Fern from our API Definition.

export const ListCustomerTransactionsRequestTransactionType = {
    Recharge: "recharge",
    Debit: "debit",
    Refund: "refund",
    Transfer: "transfer",
} as const;
export type ListCustomerTransactionsRequestTransactionType =
    (typeof ListCustomerTransactionsRequestTransactionType)[keyof typeof ListCustomerTransactionsRequestTransactionType];
