// This file was auto-generated by Fern from our API Definition.

export interface ListCustomerNumbersResponse {
    items: unknown[];
    page: number;
    per_page: number;
    total: number;
    account_auth_id: string;
}
