// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "cdr_XXXXXXXXXX",
 *         status: "live"
 *     }
 */
export interface GetLiveCallRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    status: Vobiz.GetLiveCallRequestStatus;
}
