// This file was auto-generated by Fern from our API Definition.

import type * as Vobiz from "../../../../index.js";

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         status: "live"
 *     }
 */
export interface ListQueuedCallsRequest {
    /** Your account Auth ID */
    auth_id: string;
    status: Vobiz.ListQueuedCallsRequestStatus;
}
