// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         conference_name: "conference_name",
 *         member_id: "member_id"
 *     }
 */
export interface UnmuteMemberRequest {
    /** Your account Auth ID */
    auth_id: string;
    conference_name: string;
    member_id: string;
}
