// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "call_uuid",
 *         service_url: "wss://your-server.com/ws",
 *         bidirectional: true,
 *         audio_track: "both"
 *     }
 */
export interface StartStreamRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    service_url: string;
    bidirectional?: boolean;
    audio_track?: StartStreamRequest.AudioTrack;
    audio_format?: StartStreamRequest.AudioFormat;
}

export namespace StartStreamRequest {
    export const AudioTrack = {
        Inbound: "inbound",
        Outbound: "outbound",
        Both: "both",
    } as const;
    export type AudioTrack = (typeof AudioTrack)[keyof typeof AudioTrack];
    export const AudioFormat = {
        Pcm: "pcm",
        Mulaw: "mulaw",
    } as const;
    export type AudioFormat = (typeof AudioFormat)[keyof typeof AudioFormat];
}
