// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         auth_id: "MA_XXXXXX",
 *         call_uuid: "call_uuid",
 *         stream_id: "stream_id"
 *     }
 */
export interface StopStreamRequest {
    /** Your account Auth ID */
    auth_id: string;
    call_uuid: string;
    stream_id: string;
}
